/* eslint-disable import/prefer-default-export */
export const pokemonList: Array<Pokemon> = [
    { id: 1, name: 'bulbasaur', type: ['grass', 'poison'] },
    { id: 2, name: 'ivysaur', type: ['grass', 'poison'] },
    { id: 3, name: 'venusaur', type: ['grass', 'poison'] },
    { id: 4, name: 'charmander', type: ['fire'] },
    { id: 5, name: 'charmeleon', type: ['fire'] },
    { id: 6, name: 'charizard', type: ['fire', 'flying'] },
];

export const Types: Array<string> = [
    'normal',
    'fire',
    'water',
    'electric',
    'grass',
    'ice',
    'fighting',
    'poison',
    'ground',
    'flying',
    'psychic',
    'bug',
    'rock',
    'ghost',
    'dragon',
    'dark',
    'steel',
    'fairy',
];

export const mockEvolution = [
    {
        pokemon: 'wurmple',
        evolved_pokemon: 'silcoon',
        level: 7,
        held_item: null,
        use_item: null,
        time: null,
        friendship: false,
        move: null,
        trade: false,
        other: 'based on personality',
    },
    {
        pokemon: 'wurmple',
        evolved_pokemon: 'cascoon',
        level: 7,
        held_item: null,
        use_item: null,
        time: null,
        friendship: false,
        move: null,
        trade: false,
        other: 'based on personality',
    },
    {
        pokemon: 'silcoon',
        evolved_pokemon: 'beautifly',
        level: 10,
        held_item: null,
        use_item: null,
        time: null,
        friendship: false,
        move: null,
        trade: false,
        other: null,
    },
    {
        pokemon: 'cascoon',
        evolved_pokemon: 'duxtox',
        level: 10,
        held_item: null,
        use_item: null,
        time: null,
        friendship: false,
        move: null,
        trade: false,
        other: null,
    },
];

export const tree = [
    {
        name: 'wurmple',
        data: null,
        children: [
            {
                name: 'silcoon',
                data: {
                    pokemon: 'wurmple',
                    evolved_pokemon: 'silcoon',
                    level: 7,
                    held_item: null,
                    use_item: null,
                    time: null,
                    friendship: false,
                    move: null,
                    trade: false,
                    other: 'based on personality',
                },
                children: [
                    {
                        name: 'beautifly',
                        data: {
                            pokemon: 'silcoon',
                            evolved_pokemon: 'beautifly',
                            level: 10,
                            held_item: null,
                            use_item: null,
                            time: null,
                            friendship: false,
                            move: null,
                            trade: false,
                            other: null,
                        },
                        children: [],
                    },
                ],
            },
            {
                name: 'cascoon',
                data: {
                    pokemon: 'wurmple',
                    evolved_pokemon: 'cascoon',
                    level: 7,
                    held_item: null,
                    use_item: null,
                    time: null,
                    friendship: false,
                    move: null,
                    trade: false,
                    other: 'based on personality',
                },
                children: [
                    {
                        name: 'cascoon',
                        data: {
                            pokemon: 'silcoon',
                            evolved_pokemon: 'duxtox',
                            level: 10,
                            held_item: null,
                            use_item: null,
                            time: null,
                            friendship: false,
                            move: null,
                            trade: false,
                            other: null,
                        },
                        children: [],
                    },
                ],
            },
        ],
    },
];
